language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=mysql DATABASE_URL=mysql://root@localhost:3306/nymph_testing
  - DB=pgsql DATABASE_URL=postgres://postgres@localhost:5432/nymph_testing

mysql:
  database: nymph_testing
  user: nymph_testing
  encoding: utf8

install: composer install

before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "CREATE DATABASE nymph_testing;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS nymph_testing;" -uroot; fi

script: ./testing/run
