language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=mysql
  - DB=pgsql

mysql:
  database: nymph_testing
  user: nymph_testing
  encoding: utf8

install: composer install

before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS nymph_testing;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP USER IF EXISTS nymph_testing;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "CREATE USER nymph_testing WITH PASSWORD 'password';" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "CREATE DATABASE nymph_testing WITH OWNER=nymph_testing;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS nymph_testing;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP USER 'nymph_testing'@'localhost';" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE USER 'nymph_testing'@'localhost' IDENTIFIED BY 'password';" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE nymph_testing;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "GRANT ALL ON nymph_testing.* TO 'nymph_testing'@'localhost';" -uroot; fi

script: ./testing/run
